import 'package:flutter/cupertino.dart';

class SelectedDropdownButton{
  /*
    atributos para dropdown
   */
  final selectedAuditor = ValueNotifier('');
  final auditor = [
    'REPOSITOR',
    'PROMOTOR',
    'BRIGADA DE VALIDADE',
    'CONTROLADORIA MEDEIROS'
  ];
  final selectedSetor = ValueNotifier('');
  final setor = [
    'CANTINHO DA OFERTAS',
    'PONTO EXTRA ENTRADA',
    'RACK DE CEREAIS',
    'EXPOSITOR DE PÃES',
    'RETAGUARDA PADARIA',
    'EXPOSITOR PADARIA DIVERSOS',
    'BALCÃO DE LATICÍNIOS',
    'BALCÃO FLV',
    'PONTO DE EXTRA DE CONGELADOS',
    'ILHAS DE CONGELADOS',
    'GELADEIRA COCA PADARIA',
    'GELADEIRA COCA GRANDE',
    'GELADEIRA COCA 01',
    'GELADEIRA COCA 02',
    'GELADEIRA REQ/MARG/IOG',
    'COOLER',
    'EXPOSITOR DE CHURRASCO',
    'EXPOSITOR DE SALGADINHOS COOLER',
    'CORREDOR DE BEBIDAS',
    'CORREDOR BISCOITOS',
    'CORREDOR MATINAIS',
    'CORREDOR AUTOMOTIVO/RAÇÃO',
    'CORREDOR DE LIMPEZA',
    'CORREDOR PERFUMARIA',
    'GÔNDULA DE CONSERVAS/CONDIMENTOS E MOLHOS',
    'CORREDOR NATURAIS',
    'CORREDOR DE MASSAS',
    'CORREDOR DE BAZAR',
    'CORREDOR DE ACHOCOLATADOS/LEITE UHT',
    'GÔNDULAS BISCOITOS ESPECIAIS',
    'PONTO EXTRA FRIOS',
    'PONTO EXTRA FUNDO LOJA',
    'CHECK STAND PDV 1',
    'CHECK STAND PDV 2',
    'CHECK STAND PDV 3',
    'CHECK STAND PDV 4',
    'CHECK STAND PDV 5',
    'CHECK STAND PDV 6',
    'CHECK STAND PDV 7',
  ];
}